runtime: python
env: flex

entrypoint: python main.py

# Optional: specify additional instance settings
instance_class: F2

# Optional: configure automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 5

# Environment variables (if you need to set any)
env_variables:
  GOOGLE_CLOUD_PROJECT: "braided-shift-418211"
  BIGQUERY_DATASET_ID: "creditcard"
  BIGQUERY_TABLE_ID: "customerdata"

# Optional: network settings
network:
  session_affinity: false
  forwarded_ports:
    - 8080
