runtime: python39

env: flex  # Use the flexible environment

service: default  # Replace with your desired service name

# Configure Google Cloud Storage for deployment
deployment:
  source: .

# Optional environment variables (replace with your project ID and bucket name)
env_variables:
  GCS_BUCKET_NAME: credit-card-details

