runtime: python39

env: flex  # Use the flexible environment for easier scaling

service: your-service-name  # Replace with your desired service name

# Optional: Specify allowed HTTP methods if needed
api_version: 1
allowed_methods:
- POST

handlers:
- url: /transfer-data  # URL path for your Cloud Function
  script: main.py  # Replace with the actual filename of your Python script

